### ISSUE TITLE
Implement opa_eval_ctx_set_entrypoint

### ISSUE THREAD

**Issue by christophwille** [christophwille/dotnet-opa-wasm#15]
See https://github.com/open-policy-agent/npm-opa-wasm/blob/7d30ab746042dd9dffd3446f9cb3c031b62df791/src/opa.js#L250

**Comment by ievgenii-shepeliuk** [comment]
Yes, for OPA this is every useful feature.

**Comment by eshepelyuk** [comment]
@christophwille any estimation for this fix ?

**Comment by christophwille** [comment]
No plans wrt to timeline (I don't need it).

**Comment by christophwille** [comment]
Does anyone have good concise simple example regos to use as unit tests?

**Comment by ievgenii-shepeliuk** [comment]
This is a PR from npm-opa-wasm, I thinks regos can be extracted from there
https://github.com/open-policy-agent/npm-opa-wasm/pull/50

**Comment by christophwille** [comment]
@ievgenii-shepeliuk @eshepelyuk Please have a look at  https://github.com/christophwille/dotnet-opa-wasm/pull/17 to see if that would be an API palatable to your use case.

**Comment by eshepelyuk** [comment]
Could you add a test to call entrypoint like `example/one/myRule` ?
Otherwise LGTM, great work.
Thank you !
