### ISSUE TITLE
Implement opa_abort

### ISSUE THREAD

**Issue by christophwille** [christophwille/dotnet-opa-wasm#25]
What would be an easy .rego to force an abort to happen (unit test)? 

@srenatus sorry for bothering you yet again - I asked in https://github.com/open-policy-agent/opa/issues/3083 however I still turned up empty-handed how to nicely force an abort. I don't want to blindly implement the feature without a test.

**Comment by srenatus** [comment]
No worries! Any conflict error would trigger this, like

```rego
package p

r { true }
r = false { true }

q { r }
```
Not near a computer right now, but p/r or p/q should trigger this.

**Comment by christophwille** [comment]
Thanks, this works for opa_abort being called.

Note to self:

`string info = _envMemory.ReadNullTerminatedString(_store, addr);`

works fine, however, 

`throw new PolicyEvaluationAbortedException(info);`

then leads to 

![image](https://user-images.githubusercontent.com/344208/140279847-55f2005e-5808-4aec-9378-1985f537889d.png)

which in turn means my unit test expecting PolicyEvaluationAbortedException craps out:

```
      Expected: <Opa.Wasm.PolicyEvaluationAbortedException>
      But was:  <Wasmtime.TrapException: abort.rego:4:1: var assignment conflict
    wasm backtrace:
        0: 0xbdb7 - <unknown>!opa_abort
        1:  0x9b7 - <unknown>!opa_runtime_error
        2: 0x129d2 - <unknown>!g0.data.aborttestpkg.r
        3: 0x12a03 - <unknown>!g0.data.aborttestpkg.q
        4:  0x814 - <unknown>!eval
    
       at Wasmtime.Function.Invoke(StoreContext context, ReadOnlySpan`1 arguments)
       at Wasmtime.Function.Invoke(IStore store, Object[] arguments)
       at Opa.Wasm.OpaPolicy.Policy_eval(Int32 ctxAddr) in D:\GitWorkspace\dotnet-opa-wasm\src\Opa.Wasm\OpaPolicy.Functions.cs:line 72
       at Opa.Wasm.OpaPolicy.ExecuteEvaluate(String json, Nullable`1 entrypoint) in D:\GitWorkspace\dotnet-opa-wasm\src\Opa.Wasm\OpaPolicy.cs:line 275
       at Opa.Wasm.OpaPolicy.Evaluate(String json) in D:\GitWorkspace\dotnet-opa-wasm\src\Opa.Wasm\OpaPolicy.cs:line 225
       at Opa.Wasm.UnitTests.AbortTests.<>c__DisplayClass0_0.<AbortTest>b__0() in D:\GitWorkspace\dotnet-opa-wasm\src\Opa.Wasm.UnitTests\AbortTests.cs:line 18
       at NUnit.Framework.Assert.Throws(IResolveConstraint expression, TestDelegate code, String message, Object[] args)>
```

**Comment by christophwille** [comment]
@srenatus Now this is interesting - opa_abort is being called first (I removed my throw to test), and then TrapException from the runtime kicks in too. My question then is - what is the use case for opa_abort when the runtime would croak anyways?

**Comment by srenatus** [comment]
There's an unreachable instruction after the call to opa_abort. It's not expected to return.

**Comment by christophwille** [comment]
True, when I remove my throw the TrapException is what you just said:

```
Wasmtime.TrapException
  HResult=0x80131500
  Message=wasm trap: unreachable
wasm backtrace:
    0: 0xbdbd - <unknown>!opa_abort
    1:  0x9b7 - <unknown>!opa_runtime_error
    2: 0x129d2 - <unknown>!g0.data.aborttestpkg.r
    3: 0x12a03 - <unknown>!g0.data.aborttestpkg.q
    4:  0x814 - <unknown>!eval

```

**Comment by srenatus** [comment]
... If I remember correctly. Not on a computer, can't check.

**Comment by srenatus** [comment]
> My question then is - what is the use case for opa_abort when the runtime would croak anyways?

It conveys more information than just a naked unreachable exception.

**Comment by christophwille** [comment]
Dumping my ideas just to think out loud: 

* opa_abort gets called. I get the detailed information. If I throw, that detailed information ends up as the message for Wasmtime.TrapException in Policy_eval. Otherwise only the generic info is available there.
* So I don't need my custom exception class in opa_abort.
* I want the user to see the more detailed information, throw new Exception will do then.

Question is do I want to surface Wasmtime.TrapException? Or wrap it?

**Comment by christophwille** [comment]
I decided to go with Wasmtime.TrapException for the moment.
