### ISSUE TITLE
InvalidOperationException on nullable AbiMinorVersion

### ISSUE THREAD

**Issue by willhausman** [christophwille/dotnet-opa-wasm#28]
https://github.com/christophwille/dotnet-opa-wasm/blob/d3fb148e999b70fadd21a4fdcf59816a6b8d5034/src/Opa.Wasm/OpaPolicy.cs#L260

You may not deem this worthy of fixing, but since abi versioning wasn't enabled in the opa cli until 0.27, wasms built on prior versions have to pass `disableFastEvaluate = true` without any indication as to why.  Do you accept PRs? A simple null check on the AbiMinorVersion should suffice to get around this option.  Alternatively, some constraints on the wasm versions of OPA supported by individual versions of the Opa.Wasm nuget package would be nice.

**Comment by christophwille** [comment]
Yes, that is a missing null check. I thought I had an Elvis there...
