### ISSUE TITLE
Help needed around custom functions

### ISSUE THREAD

**Issue by noobed7** [christophwille/dotnet-opa-wasm#29]
Hello,
I've stumbled upon this repository and was wondering if you could clarify some of the code there?
At first it was complicated for me to understand how custom built-in functions work, but then I figured that the capabilities.json played a role to declare a function structure for the `build -t wasm` to recognize it. Also with the help of the field _registeredBuiltins we declare a callback function that's purely c#. 
The question that is bugging me is how in general wasmtime work.  For example:
`
_linker.Define(OpaConstants.Module, OpaConstants.Builtin4, Function.FromCallback(_store,
				(Caller caller, int builtinId, int opaCtxReserved, int addr1, int addr2, int addr3, int addr4) =>
				{
					return CallBuiltin(builtinId, opaCtxReserved, addr1, addr2, addr3, addr4);
				})
			);
`
here we define an item to the linker (still hard to grasp this), but 
* why do we use those constants opa_builtin0 - opa_builtin4?
* `CallBuiltin(int builtinId, int opaCtxReserved, int addr1, int addr2, int addr3, int addr4)` - what are those arguments and how do you understand addresses? 
* does `private string DumpJson(int addrResult)` reads a c++ string starting from that `addrResult` in memory?
* same for `private int LoadJson(string json)` - do I understand it correctly - we write another c++ string into memory, take that address and pass it to `Policy_opa_json_parse` which uses it to give us evaluation?

Great comment on this link https://webassembly.github.io/wabt/demo/wasm2wat/ it allowed me to see those
![image](https://user-images.githubusercontent.com/35348755/144198673-e2340e89-cac1-4cca-8a10-ab8399769d02.png)
but I lack understanding from the documentation what are they needed for.

Hope this question might help others who are trying to figure things out.

Cheers

**Comment by christophwille** [comment]
A good primer is reading https://github.com/open-policy-agent/opa/blob/main/docs/content/wasm.md - but there is no C++ anywhere (malloc could give the wrong impression though)

Now as for the builtins - all callbacks from Wasm redirect to one of the CallBuiltin C# overloads (that's what the Linker is used for). Say you have a builtin called "mybuiltinfunc": yes, you need to provide it for rego compilation via capabilities.json to the OPA executable. The resulting Web Assembly module is loaded by this library, and on execution will call into the library's callback based on parameters. Now, if you as caller didn't provide the "mybuiltinfunc" Func, it will throw - you will have needed to provided it beforehand via RegisterBuiltin - please see https://github.com/christophwille/dotnet-opa-wasm/blob/master/src/Opa.Wasm.UnitTests/BuiltinTests.cs for a couple samples.
