### ISSUE TITLE
Address types

### ISSUE THREAD

**Issue by willhausman** [christophwille/dotnet-opa-wasm#32]
Disclaimer: I have done 0 research into this question.

Are the address pointers to Wasmtime memory truly `int`, not `uint`? Not sure why those would be signed integers.

**Comment by christophwille** [comment]
I took the info from the interface definitions, much like everyone else, eg: https://github.com/open-policy-agent/golang-opa-wasm/blob/master/opa/bindings.go

**Comment by willhausman** [comment]
Found the line in the documentation in this section of the documentation. https://github.com/open-policy-agent/opa/blob/main/docs/content/wasm.md#exports

> The addresses passed and returned by the policy modules are 32-bit integer offsets into the shared memory region.
