### ISSUE TITLE
.NET 6 TFM Change

### ISSUE THREAD

**Issue by christophwille** [christophwille/dotnet-opa-wasm#40]
https://github.com/bytecodealliance/wasmtime-dotnet/pull/94

This will also mean a TFM change here. Just a quick roll call for current issue reporters/contributors: @willhausman @ben-page @iinuwa - any of your solutions using dotnetopawasm not on .NET 6.0?

**Comment by willhausman** [comment]
Upgrades in process.

**Comment by iinuwa** [comment]
No, my projects are still experimental and on .NET 6.

**Comment by christophwille** [comment]
0.30 will have the TFM change
