### ISSUE TITLE
Please recommend the approach for the integrating OPA into my standalone web app written in ASP.net Core

### ISSUE THREAD

**Issue by rajamanohar** [christophwille/dotnet-opa-wasm#49]
Hi there
I have been looking for integrating policy engine into my standalone web application written in C#. I have come across OPA, but it is written in Go. I don't want to create DLL for Go lib and write a C# wrapper around it. 

Another approach, I have seen is this dotnet-opa-wasm. In my useCase, I need to call policy engine from backend C# code to evaluate and get the decision out from the engine. It doesn't require DOM access from WASM.

Since there is no GC in WASM, how safe it is to use this wasm lib in Production application?

**Comment by christophwille** [comment]
Another option is https://github.com/anderseknert/awesome-opa#net which calls out to a separately running OPA instance. Which might be the best option when it comes to auditing.
