### ISSUE TITLE
 Parsing failed if json data contains Cyrillic 

### ISSUE THREAD

**Issue by nigma143** [christophwille/dotnet-opa-wasm#52]
var module = OpaPolicyModule.Load("policy.wasm", _opaEngine);
 using var opaPolicy = module.CreatePolicyInstance();

 opaPolicy.SetDataJson("{\"User\": \"Россия\"}"); <--  Parsing failed exception

**Comment by christophwille** [comment]
https://github.com/christophwille/dotnet-opa-wasm/blob/a0a1da3211842370fa99a419b3c5b6ff27406613/src/Opa.Wasm/OpaPolicy.cs#L313

That calls into LoadJson

https://github.com/christophwille/dotnet-opa-wasm/blob/a0a1da3211842370fa99a419b3c5b6ff27406613/src/Opa.Wasm/OpaPolicy.cs#L326-L338

So looks the parsing error actually occurs inside OPA.

**Comment by nigma143** [comment]
#53
