### ISSUE TITLE
Initial Memory Size

### ISSUE THREAD

**Issue by ernst1j** [christophwille/dotnet-opa-wasm#54]
We have found an issue when loading large policies causing the Wasmtime to throw a "wasm trap: out of bounds memory access" error.  We were able to pull in the source code into our project and change the minimum memory page size from 2 to 3 and that resolved our issue.  We also tried updating the maximum memory size, but that did not seem to resolve the issue.  

Unless we are doing something wrong, we would like to have an optional parameter on the CreatePolicyInstance to be able to specify the initial page size.

**Comment by christophwille** [comment]
I can add a ctor parameter for that; could you tell me actually which line raised the wasm trap (curiosity)?

**Comment by christophwille** [comment]
Does the change in the linked commit work for you?

**Comment by ernst1j** [comment]
@christophwille, yes that will work great.  Thanks for the quick response.

**Comment by christophwille** [comment]
Shipped in 0.90.
