### ISSUE TITLE
OPA compile API support

### ISSUE THREAD

**Issue by SPopenko** [christophwille/dotnet-opa-wasm#9]
Hi @christophwille thanks for nice tool! Does this module support partial evaluation via compile opa API: https://www.openpolicyagent.org/docs/latest/rest-api/#compile-api ?

If not do you plan to extend module to support that? Or in general does opa wasm support partial evaluation?

Thanks!

**Comment by christophwille** [comment]
OPA WASM is a very small subset. I haven't seen any of this on the WASM side.
